### ISSUE TITLE
EmailTemplate fails to deploy after building the package

### ISSUE THREAD

**Issue by jordanebachelet** [scolladon/sfdc-generate-package#1]
Hello,

I use this module in a gulp task, calling it before the deploy task from "gulp-jsforce-deploy" module.
When deploying my package based on the generated package.xml, The deployment status on the instance fails because the module added a _<members>_ node with the name of the folder where my Email Templates are located.

Hereafter the gulp taks:
```
gulp.task('build-package', () => {
    sgp({
        apiVersion: forceConfig.apiVersion,
        src: forceConfig.src,
        output: forceConfig.src
    });
});

gulp.task('deploy', ['build-package'], () => {
    gulp.src('./' + forceConfig.src + '/**', { base: '.' })
      .pipe(zip('package.zip'))
      .pipe(forceDeploy({
          username: forceConfig.username,
          password: forceConfig.password,
          loginUrl: forceConfig.url,
          version: forceConfig.apiVersion,
          pollInterval: forceConfig.pollInterval,
          pollTimeout: forceConfig.pollTimeout
      }));
});
```
My folder structure is like this:
| emails
--| unfiled$public
----| myTemplate1
----| myTemplate2

Here is the generated package.xml file (EmailTemplate part):
```
<types>
    <members>unfiled$public</members>
    <members>unfiled$public/myTemplate1</members>
    <members>unfiled$public/myTemplate2</members>
    <name>EmailTemplate</name>
 </types>
```
The issue in the deployment status is **An object 'unfiled$public' of type EmailTemplate was named in package.xml, but was not found in zipped directory**.

I think you should juste escape the potential folder structure between the _emails_ folder and the templates files.

Let me know if you need further details.

**Comment by scolladon** [comment]
Very good tips ! Thanks, I will try it.
I’ll let you know

**Comment by scolladon** [comment]
I deployed a fix
