### ISSUE TITLE
CompactLayout as WorkflowAlert

### ISSUE THREAD

**Issue by adamantine-dev** [scolladon/sfdc-generate-package#10]
Hi Sebastien.

I've found the issue: your package create an **WorkflowAlert** node in the _package.xml_ file instead of a **CompactLayout** node:

https://github.com/scolladon/sfdc-generate-package/blob/238b1d4d6dd873014160c9197f610432c62c7550/lib/utils/metadata.js#L80

**Comment by scolladon** [comment]
Nice catch !!
I fix it in the morning
