### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by elitrGit** [scolladon/sfdc-generate-package#18]
Hi,

Translations files are ignored and cannot be found in the package.xml after running the script.
examples:
src\translations\en_US.transltion
src\standardValueSetTranslaions\CaseStatus-en_US.standardValueSetTranslation

API Version: 43.0

Thanks!

**Comment by elitrGit** [comment]
seems like custom permissions are also ignored (src/customPermissions/*.customPermission)

**Comment by scolladon** [comment]
@elitrGit does this commit e1e5a7f fix your issue ?

**Comment by elitrGit** [comment]
Thanks!

**Comment by scolladon** [comment]
@elitrGit  Is it fixed ?

**Comment by elitrGit** [comment]
yes. Thanks
