### ISSUE TITLE
LightningComponentBundle is not generated

### ISSUE THREAD

**Issue by enriquedurango** [scolladon/sfdc-generate-package#38]
Hi guys when adding  Lightning Web Components to the source (LWC folder), the "LightningComponentBundle" type is not generated on the package.xml file.

Thanks in advance

**Comment by enriquedurango** [comment]
sorry guys, just found out that when using the api version option it works.

-a, --api-version            salesforce API version [40.0]

Thanks

**Comment by scolladon** [comment]
No problem,

Thanks for warning !
