### ISSUE TITLE
Request for adding additional Metadata : NavigationMenu and Audience 

### ISSUE THREAD

**Issue by Manisshkumar** [scolladon/sfdc-generate-package#43]
Hi Sebastien,

Thank you for the tool for generating package,
We would like to add few more metadata on for project.

  "navigationMenus": {
    "xmlName": "NavigationMenu",
    "minApiVersion": 27.0,
    "maxApiVersion": 52.0
  },
  "audience": {
    "xmlName": "Audience",
    "minApiVersion": 27.0,
    "maxApiVersion": 52.0
  },

Kindly consider.

**Comment by scolladon** [comment]
Hi @Manisshkumar !

Thanks for the suggestion !
It is just added, check the latest version.

**Comment by Manisshkumar** [comment]
Thank you so much for your quick response.
