### ISSUE TITLE
Unknown type name 'ActionOverride' specified in package.xml

### ISSUE THREAD

**Issue by xgeek-net** [scolladon/sfdc-generate-package#8]
Hi, I was using jsforce to deploy metadata base on api ver 37.0 and it occurred Unknown type error as title.

**Comment by scolladon** [comment]
Hi, I think the package.xml misses the related object where the ActionOverride is applied.
Documentation specified it [here](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/actionoverride.htm?search_text=actionoverride) 
> You can access ActionOverride only by accessing its encompassing CustomObject

No ?

**Comment by xgeek-net** [comment]
@scolladon 

ActionOverride is not necessary because it will be deployed with Object.
Here is a sample you can reproduce the error, even deploy with ant migration tool.
[src.zip](https://github.com/scolladon/sfdc-generate-package/files/2231350/src.zip)

**Comment by scolladon** [comment]
Humm, you think the ActionOverride should not appear in the package.xml as it already appear if the related object appeared in the CustomObject type right ?
It should be removed from the metadata.js file and the program should not treat it ?

**Comment by xgeek-net** [comment]
@scolladon 

Yeah, if Object has already been assigned in package.xml then ActionOverride should not appear, No?
If you can show me some sample metadata that will be great.

**Comment by scolladon** [comment]
Yep I agree. And as if you package ActionOverride, the Object will appear, it is not required to add ActionOverride to the package.xml used for deploy
